"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ErrorIds = (function () {
    function ErrorIds() {
    }
    return ErrorIds;
}());
ErrorIds.unableToRetrieveFileContent = '/errors/UnableToRetrieveFileContent';
ErrorIds.deserializingKudusFunctionList = '/errors/deserializingKudusFunctionList';
ErrorIds.unableToRetrieveFunctionsList = '/errors/unableToRetrieveFunctionsList';
ErrorIds.unableToSaveFileContent = '/errors/unableToSaveFileContent';
ErrorIds.unableToDeleteFile = '/errors/unableToDeleteFile';
ErrorIds.unableToCreateFunction = '/errors/unableToCreateFunction';
ErrorIds.unableToDeleteFunction = '/errors/unableToDeleteFunction';
ErrorIds.unableToRetrieveSecretsFileFromKudu = '/errors/unableToRetrieveSecretsFileFromKudu';
ErrorIds.unableToRetrieveRuntimeConfig = '/errors/unableToRetrieveRuntimeConfig';
ErrorIds.unableToUpdateRuntimeConfig = '/errors/unableToUpdateRuntimeConfig';
ErrorIds.unableToUpdateFunction = '/errors/unableToUpdateFunction';
ErrorIds.unableToRetrieveFunction = '/errors/unableToRetrieveFunction';
ErrorIds.unableToDecryptKeys = '/errors/unableToDecryptKeys';
ErrorIds.unableToRetrieveRuntimeKeyFromScm = '/errors/unableToRetrieveRuntimeKeyFromScm';
ErrorIds.unableToRetrieveRuntimeKeyFromRuntime = '/errors/unableToRetrieveRuntimeKeyFromRuntime';
ErrorIds.unableToRetrieveDirectoryContent = '/errors/unableToRetrieveDirectoryContent';
ErrorIds.unableToSyncTriggers = '/errors/unableToSyncTriggers';
ErrorIds.unableToCallDiagnoseApi = '/errors/unableToCallDiagnoseApi';
ErrorIds.functionRuntimeIsUnableToStart = '/errors/functionRuntimeIsUnableToStart';
ErrorIds.unableToRetrieveFunctionKeys = '/errors/unableToRetrieveFunctionKeys';
ErrorIds.unableToCreateFunctionKey = '/errors/unableToCreateFunctionKey';
ErrorIds.unableToCreateSwaggerKey = '/errors/unableToCreateSwaggerKey';
ErrorIds.unableToDeleteFunctionKey = '/errors/unableToDeleteFunctionKey';
ErrorIds.unableToRenewFunctionKey = '/errors/unableToRenewFunctionKey';
ErrorIds.proxyWithSameNameAlreadyExists = '/errors/proxyWithSameNameAlreadyExists';
ErrorIds.proxySchemaValidationFails = '/errors/proxySchemaValidationFails';
ErrorIds.errorParsingConfig = '/errors/errorParsingConfig';
ErrorIds.generalFunctionErrorFromHost = '/errors/generalFunctionErrorFromHost';
ErrorIds.generalHostErrorFromHost = '/errors/generalHostErrorFromHost';
ErrorIds.tryAppServiceError = '/errors/tryAppServiceError';
ErrorIds.corsNotConfigured = '/errors/corsNotConfigured';
ErrorIds.errorCallingDiagnoseApi = '/errors/errorCallingDiagnoseApi';
ErrorIds.userDoesntHaveAccess = '/errors/userDoesntHaveAccess';
ErrorIds.unauthorizedTalkingToRuntime = '/errors/unauthorizedTalkingToRuntime';
ErrorIds.applicationOffline = '/errors/applicationOffline';
ErrorIds.failedToQueryArmResource = '/errors/failedToQueryArmResource';
ErrorIds.unableToGetSystemKey = '/errors/unableToGetSystemKey';
ErrorIds.unableToUpdateSwaggerData = '/errors/unableToUpdateSwaggerData';
ErrorIds.unableToDeleteSwaggerData = '/errors/unableToDeleteSwaggerData';
ErrorIds.unableToloadGeneratedAPIDefinition = '/errors/unableToloadGeneratedAPIDefinition';
ErrorIds.failedToCreateApp = '/errors/unableToCreateApp';
ErrorIds.failedToCreateSlot = '/errors/unableToCreateSlot';
ErrorIds.malformedAPIDefinition = '/errors/malformedAPIDefinition';
ErrorIds.passThroughApiError = '/errors/passThroughApiError';
ErrorIds.unableToUpdateFunctionAppEditMode = '/errors/unableToUpdateFunctionAppEditMode';
ErrorIds.unableToPopulateSlotsList = '/errors/unableToPopulateSlotsList';
exports.ErrorIds = ErrorIds;
//# sourceMappingURL=error-ids.js.map